project:
  name: "example"

components:
  nginx:
    name: my_nginx
    type: WebServer/nginx
    external-port: 8080
    internal-port: 80
    config:
      locations:
        - kooft:flask/kooft

  flask:
    name: my_flask
    type: WebApplication/flask
    internal-port: 8000
    config:
      locations:
        - kooft:hello-world

